//-----------------------------------------------------------------------
// <copyright file="MockThrowingExceptionInEventHandler.cs" company="NMock2">
//
//   http://www.sourceforge.net/projects/NMock2
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// </copyright>
// This is the easiest way to ignore StyleCop rules on this file, even if we shouldn't use this tag:
// <auto-generated />
//-----------------------------------------------------------------------
namespace NMock2.AcceptanceTests
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class MockThrowingExceptionInEventHandler : AcceptanceTestBase
    {
        [Test]
        [ExpectedException(typeof(ApplicationException), ExpectedMessage = "got you!")]
        public void ExceptionsInEventHandlersAreNotWrappedInInternalExceptions()
        {
            IEventProvider eventProvider = Mocks.NewMock<IEventProvider>();
            IExceptionThrower exceptionThrower = Mocks.NewMock<IExceptionThrower>();

            Expect.Once.On(eventProvider).EventAdd("Event");
            Expect.Once.On(exceptionThrower).Method("ThrowException").Will(Throw.Exception(new ApplicationException("got you!")));

            eventProvider.Event += delegate { exceptionThrower.ThrowException(); };

            Fire.Event("Event").On(eventProvider).With(null, EventArgs.Empty);
        }

        public interface IEventProvider
        {
            event EventHandler Event;
        }

        public interface IExceptionThrower
        {
            void ThrowException();
        }
    }
}
